Vagrant.configure("2") do |config|
  config.vm.provider :virtualbox do |vbox|
    vbox.memory = 1024
    vbox.cpus = 2
    vbox.gui =true
    vbox.check_guest_additions = true

  end


  config.vm.define "kali" do |kali|
    kali.vm.box = "elrey741/kali-linux_amd64"
    kali.vm.hostname="kali.example.com"
    kali.vm.network "private_network", ip: "192.168.33.10"
  end

  config.vm.define "securityonion" do |securityonion|
    securityonion.vm.box = "rothoma2/security-onion"
    securityonion.vm.hostname="securityonion.example.com"
    securityonion.vm.network "private_network", ip: "192.168.33.10"
  end


end
